# universe.py
# NSE 200 Stock Universe (Cash Market)

NSE_200 = [
    "ACC", "ADANIENT", "ADANIPORTS", "ALKEM", "AMBUJACEM",
    "APOLLOHOSP", "APOLLOTYRE", "ASHOKLEY", "ASIANPAINT",
    "ASTRAL", "ATUL", "AUBANK", "AUROPHARMA", "AXISBANK",

    "BAJAJ-AUTO", "BAJAJFINSV", "BAJFINANCE", "BALKRISIND",
    "BANDHANBNK", "BANKBARODA", "BATAINDIA", "BERGEPAINT",
    "BHARATFORG", "BHARTIARTL", "BHEL", "BIOCON", "BOSCHLTD",
    "BPCL", "BRITANNIA",

    "CANBK", "CHAMBLFERT", "CHOLAFIN", "CIPLA", "COALINDIA",
    "COFORGE", "COLPAL", "CONCOR", "COROMANDEL",
    "CROMPTON", "CUMMINSIND",

    "DABUR", "DALBHARAT", "DEEPAKNTR", "DIVISLAB",
    "DIXON", "DLF", "DRREDDY",

    "EICHERMOT", "ESCORTS", "EXIDEIND",

    "FEDERALBNK",

    "GAIL", "GLAND", "GLENMARK", "GMRINFRA", "GNFC",
    "GODREJCP", "GODREJPROP", "GRASIM", "GUJGASLTD",

    "HAVELLS", "HCLTECH", "HDFCAMC", "HDFCBANK",
    "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HINDPETRO",
    "HINDUNILVR", "HONAUT",

    "ICICIBANK", "ICICIGI", "ICICIPRULI", "IDFCFIRSTB",
    "IEX", "IGL", "INDHOTEL", "INDIACEM", "INDIAMART",
    "INDIGO", "INDUSINDBK", "INDUSTOWER", "INFY",
    "INTELLECT", "IOC", "IRCTC", "ITC",

    "JINDALSTEL", "JKCEMENT", "JSWENERGY", "JSWSTEEL",

    "KOTAKBANK",

    "LALPATHLAB", "LAURUSLABS", "LICHSGFIN", "LT",
    "LTIM", "LTTS", "LUPIN",

    "M&M", "M&MFIN", "MANAPPURAM", "MARICO", "MARUTI",
    "MCDOWELL-N", "METROPOLIS", "MFSL", "MGL",
    "MINDTREE", "MOTHERSUMI", "MPHASIS", "MRF",

    "MUTHOOTFIN",

    "NAM-INDIA", "NATIONALUM", "NAUKRI", "NAVINFLUOR",
    "NESTLEIND", "NMDC", "NTPC",

    "OBEROIRLTY", "ONGC",

    "PAGEIND", "PEL", "PETRONET", "PIDILITIND",
    "PIIND", "PNB", "POLYCAB", "POWERGRID",
    "PVRINOX",

    "RAMCOCEM", "RELIANCE", "SAIL", "SBICARD",
    "SBILIFE", "SBIN", "SHREECEM", "SIEMENS",
    "SRF", "SUNPHARMA", "SUNTV",

    "TATACHEM", "TATACOMM", "TATACONSUM", "TATAELXSI",
    "TATAMOTORS", "TATAPOWER", "TATASTEEL",
    "TECHM", "TITAN", "TORNTPHARM", "TORNTPOWER",

    "TRENT", "TVSMOTOR",

    "UBL", "ULTRACEMCO", "UPL",

    "VEDL", "VOLTAS",

    "WIPRO",

    "ZEEL", "ZYDUSLIFE"
]
