# universe.py
# NSE 200 universe (cash market symbols)

NSE_200 = [
    "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT",
    "AXISBANK", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV",
    "BPCL", "BHARTIARTL", "BRITANNIA", "CIPLA",
    "COALINDIA", "DIVISLAB", "DRREDDY", "EICHERMOT",
    "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE",
    "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK",
    "ITC", "INDUSINDBK", "INFY", "JSWSTEEL",
    "KOTAKBANK", "LT", "M&M", "MARUTI",
    "NESTLEIND", "NTPC", "ONGC", "POWERGRID",
    "RELIANCE", "SBILIFE", "SBIN", "SUNPHARMA",
    "TATAMOTORS", "TATASTEEL", "TCS", "TECHM",
    "TITAN", "ULTRACEMCO", "UPL", "WIPRO",

    # Mid / Large caps (remaining NSE 200)
    "ABB", "ABCAPITAL", "ACC", "ADANIGREEN",
    "ADANIPOWER", "AMBUJACEM", "AUROPHARMA", "BANDHANBNK",
    "BANKBARODA", "BERGEPAINT", "BIOCON", "BOSCHLTD",
    "CANBK", "CHOLAFIN", "COLPAL", "CONCOR",
    "DABUR", "DLF", "GAIL", "GLENMARK",
    "GODREJCP", "GODREJPROP", "HAVELLS", "ICICIGI",
    "ICICIPRULI", "IDFCFIRSTB", "IGL", "INDIGO",
    "JINDALSTEL", "LUPIN", "MARICO", "MINDTREE",
    "MUTHOOTFIN", "NMDC", "OFSS", "PEL",
    "PIDILITIND", "PNB", "POLYCAB", "SAIL",
    "SIEMENS", "SRF", "TORNTPHARM", "TRENT",
    "TVSMOTOR", "UBL", "VEDL", "ZEEL"
]

def get_universe():
    """Safe accessor"""
    return NSE_200
